CREATE INDEX index_id ON CUSTOMER USING btree(name);
CREATE INDEX index_name ON CUSTOMER USING hash(id);

EXPLAIN SELECT ID FROM CUSTOMER WHERE ID = 40001 OR ID = 800000;

EXPLAIN SELECT id FROM CUSTOMER WHERE name LIKE 'S%';

EXPLAIN SELECT address FROM CUSTOMER WHERE name='Jeffrey Thompson';
